# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_serial', models.IntegerField(help_text='Chapter No.')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('chapter_name', models.CharField(max_length=120)),
                ('section', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['chapter_serial'],
            },
        ),
        migrations.CreateModel(
            name='Numerical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerical_serial', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Chapter')),
            ],
            options={
                'ordering': ['numerical_serial'],
            },
        ),
        migrations.CreateModel(
            name='SAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_serial', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Chapter')),
            ],
            options={
                'ordering': ['question_serial'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('faculty', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_serial', models.IntegerField()),
                ('title', models.CharField(max_length=360)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('remarks', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['subsection_serial'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_serial', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Chapter')),
            ],
            options={
                'ordering': ['subtopic_serial'],
            },
        ),
        migrations.AddField(
            model_name='subsection',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic'),
        ),
        migrations.AddField(
            model_name='saq',
            name='subtopic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic'),
        ),
        migrations.AddField(
            model_name='numerical',
            name='subtopic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subject'),
        ),
    ]
