# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20171025_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection_image',
            name='subtopic',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic'),
            preserve_default=False,
        ),
    ]
