# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_subsection_image_subtopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsection_image',
            new_name='SubsectionImage',
        ),
    ]
