# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0008_auto_20171104_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerical',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_numerical', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='numerical',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_numerical', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='numerical',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_numerical', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saq',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_saq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saq',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_saq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saq',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_saq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_subsection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_subsection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsection',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_subsection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsectionimage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_subsection_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsectionimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_subsection_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsectionimage',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_subsection_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
