# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20171104_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerical',
            name='remarks',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='saq',
            name='remarks',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='remarks',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='remarks',
            field=models.CharField(blank=True, max_length=360),
        ),
    ]
