# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20171105_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsectionimage',
            options={'ordering': ['image_serial']},
        ),
    ]
