# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20171105_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='poster_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=None, width_field='width_field'),
        ),
    ]
