# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20171116_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectionimage',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsection_image', to='cms.Subsection'),
        ),
        migrations.AlterField(
            model_name='subsectionimage',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsection_image', to='cms.Subtopic'),
        ),
    ]
