# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20171123_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='poster_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='numerical',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='saq',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='subject',
            name='poster_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='poster_text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
