# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20171203_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
