# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:18
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='poster_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=cms.models.poster_upload, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='numerical',
            name='display_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=cms.models.image_upload, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='saq',
            name='display_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=cms.models.image_upload, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='poster_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=cms.models.poster_upload, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='poster_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=cms.models.poster_upload, width_field='width_field'),
        ),
    ]
