# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:19
from __future__ import unicode_literals

import cms.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20171205_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='poster_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=cms.models.poster_upload),
        ),
    ]
