# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:06
from __future__ import unicode_literals

import cms.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20171208_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='poster_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=cms.models.poster_upload),
        ),
    ]
