# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:46
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20171208_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='poster_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=cms.models.poster_upload, width_field='width_field'),
        ),
    ]
