# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0007_auto_20171029_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempNumerical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerical_serial', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('display_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Chapter')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic')),
            ],
            options={
                'ordering': ['numerical_serial'],
            },
        ),
        migrations.CreateModel(
            name='TempSAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_serial', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('display_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Chapter')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic')),
            ],
            options={
                'ordering': ['question_serial'],
            },
        ),
        migrations.CreateModel(
            name='TempSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_serial', models.IntegerField()),
                ('title', models.CharField(max_length=360)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('remarks', models.CharField(blank=True, max_length=240)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic')),
            ],
            options={
                'ordering': ['subsection_serial'],
            },
        ),
        migrations.CreateModel(
            name='TempSubsectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_serial', models.IntegerField()),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subsection')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Subtopic')),
            ],
            options={
                'ordering': ['image_serial'],
            },
        ),
    ]
