# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempnumerical',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempsaq',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempsubsection',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempsubsectionimage',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
