# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0002_auto_20171101_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempnumerical',
            name='edited_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempsaq',
            name='edited_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempsubsection',
            name='edited_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempsubsectionimage',
            name='edited_bool',
            field=models.BooleanField(default=False),
        ),
    ]
