# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0003_auto_20171102_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempnumerical',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tempsaq',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tempsubsection',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tempsubsectionimage',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
