# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tempcms', '0004_auto_20171104_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempnumerical',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_tempNumerical', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tempsaq',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_tempSAQ', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tempsubsection',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_tempsubsection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tempsubsectionimage',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_by_tempSubsectionImage', to=settings.AUTH_USER_MODEL),
        ),
    ]
