# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0006_auto_20171104_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempsubsection',
            options={'ordering': ['subtopic']},
        ),
        migrations.AlterField(
            model_name='tempsubsection',
            name='remarks',
            field=models.CharField(blank=True, help_text='For example: HSEB 2068, HSEB 2070 Frequently asked in Entrance, etc.', max_length=360),
        ),
    ]
