# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0008_auto_20171105_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempsubsection',
            options={'ordering': ['subtopic', '-date_modified']},
        ),
    ]
