# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0010_auto_20171105_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempnumerical',
            options={'ordering': ['chapter', '-date_modified'], 'permissions': (('view_pending_numericals', 'Can see pending Numerical items'), ('approve_pending_numericals', 'Can approve pending Numerical items'))},
        ),
        migrations.AlterModelOptions(
            name='tempsaq',
            options={'ordering': ['chapter', '-date_modified'], 'permissions': (('view_pending_saqs', 'Can see pending SAQ items'), ('approve_pending_saqs', 'Can approve pending SAQ items'))},
        ),
        migrations.AlterModelOptions(
            name='tempsubsection',
            options={'ordering': ['subtopic', '-date_modified'], 'permissions': (('view_pending_subsections', 'Can see pending Subsection items'), ('approve_pending_subsections', 'Can approve pending Subsection items'))},
        ),
        migrations.AlterModelOptions(
            name='tempsubsectionimage',
            options={'ordering': ['subsection', '-date_modified'], 'permissions': (('view_pending_subsection_images', 'Can see pending Subsection Image items'), ('approve_pending_subsection_images', 'Can approve pending Subsection Image items'))},
        ),
    ]
