# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0011_auto_20171203_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempnumerical',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tempsaq',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
