# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import tempcms.models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0012_auto_20171205_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempnumerical',
            name='display_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tempcms.models.image_upload, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='tempsaq',
            name='display_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tempcms.models.image_upload, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='tempsaq',
            name='remarks',
            field=models.CharField(blank=True, help_text='E.g. HSEB 2068, HSEB 2070 Frequently asked in Entrance, etc.', max_length=360),
        ),
    ]
