# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import tempcms.models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcms', '0013_auto_20171205_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsubsectionimage',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=tempcms.models.image_upload, width_field='width_field'),
        ),
    ]
